name: test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest-cov pylint
          pip install -e .[nco]
      - name: Lint with ruff
        run: |
          ruff --format=github .
      - name: Lint with pylint
        run: |
          pylint pypdd.py
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest pypdd.py --cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
